model:
  parameters:
    encoder_name: resnet34
    encoder_weights: imagenet
    decoder_name: Unet
    in_channels: 3
    ignore_index: -1
    classes: 48 # one more to cope with the unknown
    is_sparse: true